apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dcontact-uat
resources:
  - services.yaml
  - workloads.yaml
configMapGenerator:
  - name: dcontact-uat-proxy-config
    files:
      - tenant.Caddyfile
      - platform.Caddyfile
generatorOptions:
  disableNameSuffixHash: true
