ALTER TYPE "QmAuditAction" ADD VALUE IF NOT EXISTS 'TRANSCRIPTION_STARTED';
ALTER TYPE "QmAuditAction" ADD VALUE IF NOT EXISTS 'TRANSCRIPTION_RETRY_SCHEDULED';
ALTER TYPE "QmAuditAction" ADD VALUE IF NOT EXISTS 'TRANSCRIPTION_FAILED';
ALTER TYPE "QmAuditAction" ADD VALUE IF NOT EXISTS 'TRANSCRIPTION_READY';
