#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

REPOSITORY="Kitti-Nualsalee/dcontact"
ENVIRONMENT="uat-preview"
UAT_ROOT="/opt/dcontact-uat"
TMP_SSH=""
ROLLBACK_RUN=""

cleanup() {
  [[ -n "$TMP_SSH" ]] && rm -rf "$TMP_SSH"
}
trap cleanup EXIT

require_command() {
  command -v "$1" >/dev/null 2>&1 || { warn "ต้องติดตั้ง $1 ก่อน"; exit 1; }
}

set_environment_secret() {
  local name="$1" value="$2"
  printf '%s' "$value" | gh secret set "$name" --env "$ENVIRONMENT" --repo "$REPOSITORY"
  WRITTEN_SECRET+=("$ENVIRONMENT/$name")
  printf '  %s✓ set%s environment secret %s\n' "$GREEN" "$RESET" "$name"
}

setup_ssh() {
  TMP_SSH="$(mktemp -d)"
  printf '%s\n' "$UAT_SSH_PRIVATE_KEY" >"$TMP_SSH/key"
  printf '%s\n' "$UAT_SSH_KNOWN_HOSTS" >"$TMP_SSH/known_hosts"
  chmod 600 "$TMP_SSH/key" "$TMP_SSH/known_hosts"
}

uat_ssh() {
  ssh -i "$TMP_SSH/key" -o BatchMode=yes -o IdentitiesOnly=yes \
    -o UserKnownHostsFile="$TMP_SSH/known_hosts" -o StrictHostKeyChecking=yes \
    "$UAT_SSH_USER@$UAT_SSH_HOST" "$@"
}

banner "E1.16 · UAT acceptance"

stage "ตรวจ prerequisites และขอบเขต"
require_command gh
require_command git
require_command ssh
gh auth status >/dev/null
MAIN_SHA="$(gh api "repos/$REPOSITORY/commits/main" --jq .sha)"
LOCAL_SHA="$(git rev-parse HEAD)"
[[ "$LOCAL_SHA" == "$MAIN_SHA" ]] || { warn "ต้อง checkout final main ($MAIN_SHA) ก่อนรัน wizard"; exit 1; }
ask TENANT_SLUG "Tenant slug สำหรับ UAT (ห้ามเป็น tenant ของ #77):"
[[ "$TENANT_SLUG" =~ ^[a-z0-9][a-z0-9-]{1,62}$ ]] || { warn "tenant slug ผิดรูป"; exit 1; }
ask OPERATOR_ACTOR "Operator actor สำหรับ audit (เช่น email):"
[[ "$OPERATOR_ACTOR" =~ ^[A-Za-z0-9@._+-]+$ ]] || { warn "operator actor ผิดรูป"; exit 1; }
ask ISSUE_77_CONFIRM "พิมพ์ NOT-ISSUE-77 เพื่อยืนยันว่า tenant นี้ไม่ใช่งาน pilot #77:"
[[ "$ISSUE_77_CONFIRM" == "NOT-ISSUE-77" ]] || { warn "หยุด: ห้ามแตะ tenant ของ #77"; exit 1; }
note "acceptance SHA: $MAIN_SHA"

stage "ตั้ง GitHub environment secrets"
say "ค่าทั้งสี่มาจากเครื่อง/secret store ของเจ้าของ UAT และไม่ถูกเขียนลงไฟล์"
ask_secret UAT_SSH_PRIVATE_KEY "UAT_SSH_PRIVATE_KEY:"
ask_secret UAT_SSH_KNOWN_HOSTS "UAT_SSH_KNOWN_HOSTS:"
ask_secret UAT_SSH_HOST "UAT_SSH_HOST:"
ask_secret UAT_SSH_USER "UAT_SSH_USER:"
for value in "$UAT_SSH_PRIVATE_KEY" "$UAT_SSH_KNOWN_HOSTS" "$UAT_SSH_HOST" "$UAT_SSH_USER"; do
  [[ -n "$value" ]] || { warn "secret ห้ามว่าง"; exit 1; }
done
set_environment_secret UAT_SSH_PRIVATE_KEY "$UAT_SSH_PRIVATE_KEY"
set_environment_secret UAT_SSH_KNOWN_HOSTS "$UAT_SSH_KNOWN_HOSTS"
set_environment_secret UAT_SSH_HOST "$UAT_SSH_HOST"
set_environment_secret UAT_SSH_USER "$UAT_SSH_USER"
setup_ssh
uat_ssh "printf 'SSH_READY\\n'" | grep -qx SSH_READY

stage "Deploy final main ไป UAT"
ask INITIAL_DEPLOY "เป็น deploy ครั้งแรกหรือไม่? พิมพ์ true หรือ false:"
[[ "$INITIAL_DEPLOY" == "true" || "$INITIAL_DEPLOY" == "false" ]] || { warn "ต้องเป็น true หรือ false"; exit 1; }
confirm "dispatch uat-preview deploy ของ $MAIN_SHA ตอนนี้?" || exit 1
gh workflow run uat-preview.yml --repo "$REPOSITORY" --ref main \
  -f action=deploy -f rollback_sha= -f initial_deploy="$INITIAL_DEPLOY"
sleep 5
DEPLOY_RUN="$(gh run list --repo "$REPOSITORY" --workflow uat-preview.yml --branch main \
  --event workflow_dispatch --limit 1 --json databaseId,headSha --jq '.[0] | select(.headSha == "'"$MAIN_SHA"'") | .databaseId')"
[[ -n "$DEPLOY_RUN" ]] || { warn "หา deploy run ของ SHA นี้ไม่พบ"; exit 1; }
open_url "https://github.com/$REPOSITORY/actions/runs/$DEPLOY_RUN"
step "ให้ required reviewer อนุมัติ environment uat-preview"
gh run watch "$DEPLOY_RUN" --repo "$REPOSITORY" --exit-status

stage "Allowlist origin และเปิด embed flag"
UAT_HOST="$(gh variable get UAT_HOST --env "$ENVIRONMENT" --repo "$REPOSITORY")"
HOST_ORIGIN="https://$UAT_HOST"
uat_ssh "UAT_ROOT='$UAT_ROOT' '$UAT_ROOT/releases/$MAIN_SHA/bin/uat-deploy.sh' e1-enable '$MAIN_SHA'"
uat_ssh "UAT_ROOT='$UAT_ROOT' '$UAT_ROOT/releases/$MAIN_SHA/bin/uat-deploy.sh' smoke '$MAIN_SHA'"
open_url "$HOST_ORIGIN/?view=dphone-embedding"
step "เข้าสู่ระบบด้วยบัญชี UAT ADMIN แล้วเพิ่ม origin $HOST_ORIGIN"
step "ตั้ง screen-pop level เป็น ids และยืนยันว่า Console แสดง audit สำเร็จ"
pause "กด Enter เมื่อ allowlist พร้อม"
confirm "เปิด dphone.embed.enabled ให้ $TENANT_SLUG ตอนนี้?" || exit 1
uat_ssh "UAT_ROOT='$UAT_ROOT' '$UAT_ROOT/releases/$MAIN_SHA/bin/uat-deploy.sh' ui-flag '$MAIN_SHA' '$TENANT_SLUG' on '$OPERATOR_ACTOR'"

stage "Edge desktop + microphone acceptance"
HOST_URL="$HOST_ORIGIN/examples/dphone-host/index.html?tenant=$TENANT_SLUG"
open_url "$HOST_URL"
step "ใช้ Microsoft Edge desktop รุ่นล่าสุด เปิด DevTools และยืนยันว่า launcher v1 โหลดสำเร็จ"
step "กดเข้าสู่ระบบ: ต้องเห็น popup ของ Keycloak และ origin ของ $HOST_ORIGIN ชัดเจน"
step "กดตรวจอุปกรณ์เสียง: ต้องเห็น browser microphone prompt ของ $HOST_ORIGIN แล้วเลือก Allow"
step "ยืนยันรับสาย, screen-pop, activity ack และ click-to-call; ระหว่าง ACTIVE ทดลอง reload ปกติแล้วต้องถูกเตือน"
open_url "https://github.com/$REPOSITORY/issues/490"
step "แนบ screenshot/video ที่เห็น Edge version, origin, mic prompt และผลทั้งสี่ความสามารถใน #490"
ask EVIDENCE_URL "วาง URL ของ evidence comment ใน #490:"
[[ "$EVIDENCE_URL" == https://github.com/$REPOSITORY/issues/490* ]] || { warn "ต้องเป็น URL จาก #490"; exit 1; }

stage "Rollback embed flag"
confirm "ปิด dphone.embed.enabled เพื่อซ้อม rollback ตอนนี้?" || exit 1
uat_ssh "UAT_ROOT='$UAT_ROOT' '$UAT_ROOT/releases/$MAIN_SHA/bin/uat-deploy.sh' ui-flag '$MAIN_SHA' '$TENANT_SLUG' off '$OPERATOR_ACTOR'"
open_url "$HOST_URL"
step "reload reference host และยืนยัน iframe ถูก fail-closed; สายที่ active ก่อนปิดต้องไม่หลุดจนจบ"
pause "กด Enter เมื่อยืนยัน flag rollback แล้ว"
uat_ssh "UAT_ROOT='$UAT_ROOT' '$UAT_ROOT/releases/$MAIN_SHA/bin/uat-deploy.sh' e1-disable '$MAIN_SHA'"
uat_ssh "UAT_ROOT='$UAT_ROOT' '$UAT_ROOT/releases/$MAIN_SHA/bin/uat-deploy.sh' smoke '$MAIN_SHA'"

stage "Deployment rollback และบันทึกหลักฐาน"
warn "ขั้นนี้ต้องมี previous successful deployment record; ถ้าไม่มีให้ตอบ No และเก็บ gate นี้ไว้รอบถัดไป"
if confirm "rollback Console/API ไป deployment record ก่อนหน้า?"; then
  gh workflow run uat-preview.yml --repo "$REPOSITORY" --ref main \
    -f action=rollback -f rollback_sha= -f initial_deploy=false
  sleep 5
  ROLLBACK_RUN="$(gh run list --repo "$REPOSITORY" --workflow uat-preview.yml --branch main \
    --event workflow_dispatch --limit 1 --json databaseId --jq '.[0].databaseId')"
  open_url "https://github.com/$REPOSITORY/actions/runs/$ROLLBACK_RUN"
  gh run watch "$ROLLBACK_RUN" --repo "$REPOSITORY" --exit-status
else
  SKIPPED+=("deployment rollback: ยังไม่มี previous successful deployment record")
fi
gh issue comment 490 --repo "$REPOSITORY" --body "E1.16 manual acceptance บน main \`$MAIN_SHA\`: Edge desktop + mic/origin prompt และ flow ฝัง dphone ผ่านตาม evidence $EVIDENCE_URL; เปิด/ปิด \`dphone.embed.enabled\` ผ่าน audited operator CLI แล้ว โดย tenant ที่ใช้ไม่ใช่ #77. Deploy run: https://github.com/$REPOSITORY/actions/runs/$DEPLOY_RUN${ROLLBACK_RUN:+ · rollback run: https://github.com/$REPOSITORY/actions/runs/$ROLLBACK_RUN}"

finish
