#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: S2.7 (#368) LINE capped pilot — setup ที่ผู้ใช้ทำเองก่อน PR01/PR02/RB01
# ──────────────────────────────────────────────────────────────────────────
#
# รันจาก root ของ repo:  bash scripts/s2-line-pilot-setup.sh
# secret (token/channel secret/payload key) ไปลง macOS Keychain เท่านั้น — wizard ไม่เห็นค่า
# .env ได้แค่ reference/โหมด; หยุดก่อน actual push ซึ่ง agent ต้องแสดง proposal ให้อนุมัติ

TOTAL_STAGES=8

CHANNEL_ID=2007056595
SERVICE="d-contact.line.${CHANNEL_ID}"
REPO="Kitti-Nualsalee/dcontact"
CONSOLE="https://developers.line.biz/console/channel/${CHANNEL_ID}"

# load_env ให้คำสั่ง pnpm เห็นค่าใน .env (DATABASE_URL และ reference ที่ wizard เขียน)
load_env() { set -a; # shellcheck disable=SC1090
  . "./$ENV_FILE"; set +a; }

# keychain_has ACCOUNT: มี item แล้วหรือยัง (ไม่อ่านค่า)
keychain_has() { security find-generic-password -s "$SERVICE" -a "$1" >/dev/null 2>&1; }

# keychain_prompt ACCOUNT: ให้ `security` ถามค่าเอง (-w ท้ายสุดไม่ใส่ค่า) ค่าจึงไม่ผ่าน wizard/argv
keychain_prompt() {
  say "วางค่าเมื่อ security ถาม (ไม่แสดงบนจอ) — ระบบจะถามสองครั้ง"
  security add-generic-password -U -s "$SERVICE" -a "$1" -w
}

pilot_setup() { load_env; pnpm --silent --filter @d-contact/delivery pilot:setup "$@"; }

[[ "$(uname -s)" == "Darwin" ]] || { printf '%s\n' "wizard นี้ใช้ได้บน macOS เท่านั้น (Keychain)"; exit 1; }
[[ -f package.json && -d apps/delivery ]] || { printf '%s\n' "รันจาก root ของ repo dcontact"; exit 1; }

banner "S2 LINE pilot setup (#368)"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "Keychain: token, channel secret และ payload key"
say "ค่าลับทั้งสามเก็บใน Keychain service ${SERVICE} เท่านั้น"
open_url "${CONSOLE}/messaging-api"
step "Messaging API → Channel access token: ออก token ใหม่สำหรับ pilot ครั้งนี้"
note "แนะนำ v2.1 (อายุ ≤30 วัน, ออกด้วย JWT ตาม https://developers.line.biz/en/docs/messaging-api/generate-json-web-token/)"
note "ปุ่ม Issue ในหน้านี้ออก long-lived token — ใช้ได้เฉพาะเมื่อมี test-only exception และต้อง revoke หลัง S2"
ask CXA_S2_CREDENTIAL_KIND "ชนิด token ที่ออก (V2_1 หรือ LONG_LIVED):"
if [[ "$CXA_S2_CREDENTIAL_KIND" == "LONG_LIVED" ]]; then
  ask CXA_S2_LONG_LIVED_EXCEPTION_REF "exception ref ที่อนุมัติ long-lived (เช่น issue/comment URL):"
  write_env CXA_S2_LONG_LIVED_EXCEPTION_REF "$CXA_S2_LONG_LIVED_EXCEPTION_REF"
elif [[ "$CXA_S2_CREDENTIAL_KIND" != "V2_1" ]]; then
  warn "ต้องเป็น V2_1 หรือ LONG_LIVED"; exit 1
fi
write_env CXA_S2_CREDENTIAL_KIND "$CXA_S2_CREDENTIAL_KIND"
if ! keychain_has channel-access-token || confirm "มี channel-access-token อยู่แล้ว — แทนด้วย token ใหม่?"; then
  step "คัดลอก channel access token"
  keychain_prompt channel-access-token
fi
open_url "${CONSOLE}/basics"
step "Basic settings → Channel secret → คัดลอก"
if ! keychain_has channel-secret || confirm "มี channel-secret อยู่แล้ว — แทนด้วยค่าใหม่?"; then
  keychain_prompt channel-secret
fi
if ! keychain_has webhook-payload-key; then
  # printf เป็น builtin จึงไม่มี process ใดเห็นค่าใน argv; ค่าไม่ถูกพิมพ์ออกจอ
  printf 'add-generic-password -U -s %s -a webhook-payload-key -w %s\n' "$SERVICE" "$(openssl rand -base64 32)" | security -i >/dev/null
  say "สร้าง webhook-payload-key (32 bytes) แล้ว"
fi
for account in channel-access-token channel-secret webhook-payload-key; do
  keychain_has "$account" || { warn "ยังไม่มี $account ใน Keychain"; exit 1; }
done
printf '  %s✓%s Keychain ครบสาม item\n' "$GREEN" "$RESET"
pause

# ── 2 ────────────────────────────────────────────────────────────────────
stage "Tenant ของ pilot และ .env"
say "สร้าง dedicated test tenant (idempotent) และเขียน reference ลง ${ENV_FILE}"
[[ -f "$ENV_FILE" ]] || cp .env.example "$ENV_FILE"
ask CXA_S2_OPERATOR_REF "actor ref ของ Platform Operator (เช่น operator:<ชื่อ>):"
ask CXA_S2_COMPLIANCE_REF "actor ref ของ Compliance (ต้องต่างจาก operator):"
[[ "$CXA_S2_OPERATOR_REF" != "$CXA_S2_COMPLIANCE_REF" ]] || { warn "สอง ref ต้องต่างกัน (#358 §E)"; exit 1; }
write_env CXA_S2_OPERATOR_REF "$CXA_S2_OPERATOR_REF"
write_env CXA_S2_COMPLIANCE_REF "$CXA_S2_COMPLIANCE_REF"
write_env CXA_S2_PILOT_SENDER "d-contact-line-oa-${CHANNEL_ID}"
TENANT_ID=$(pilot_setup tenant)
write_env CXA_S2_PILOT_TENANT_ID "$TENANT_ID"
write_env LINE_WEBHOOK_TENANT_ID "$TENANT_ID"
write_env LINE_WEBHOOK_CHANNEL_ACCOUNT_ID "$CHANNEL_ID"
write_env LINE_WEBHOOK_SECRET_SOURCE keychain
write_env LINE_WEBHOOK_PAYLOAD_KEY_REF "d-contact.line.webhook-payload/v1"
DESTINATION=$(pilot_setup bot-info)
write_env LINE_WEBHOOK_DESTINATION "$DESTINATION"
pause

# ── 3 ────────────────────────────────────────────────────────────────────
stage "ngrok + API โหมด keychain + webhook URL"
say "เปิด terminal ใหม่สองอัน (ค้างไว้ตลอด pilot):"
step "terminal A:  set -a; . ./.env; set +a; pnpm --filter @d-contact/api dev"
step "terminal B:  ngrok http 3000"
warn "URL ของ ngrok ฟรีเปลี่ยนทุกครั้งที่เริ่มใหม่ — ถ้าเปลี่ยนต้องรัน wizard ขั้นนี้และขั้น gate ใหม่"
pause "เมื่อ API ขึ้นและ ngrok แสดง Forwarding https://… แล้ว กด Enter"
ask CXA_S2_NGROK_URL "วาง Forwarding URL ของ ngrok (https://…):"
ENDPOINT="${CXA_S2_NGROK_URL%/}/webhook/line"
write_env CXA_S2_WEBHOOK_ENDPOINT "$ENDPOINT"
open_url "${CONSOLE}/messaging-api"
step "Messaging API → Webhook settings → Webhook URL: ${ENDPOINT}"
step "เปิด 'Use webhook' แล้วกด Verify — ต้องได้ Success"
pause "เมื่อ Verify ผ่านแล้ว กด Enter"
DIGEST=$(pilot_setup endpoint-digest "$ENDPOINT")
write_env CXA_S2_APPROVED_WEBHOOK_ENDPOINT_DIGEST "$DIGEST"
pause

# ── 4 ────────────────────────────────────────────────────────────────────
stage "Gate ของ pilot: DISABLED → DRY_RUN → PROVIDER_CONFORMANCE"
say "Compliance เลื่อน gate พร้อม config digest ที่ผูกกับ endpoint นี้ (ยังส่งข้อความไม่ได้)"
confirm "เลื่อน gate ด้วย actor ${CXA_S2_COMPLIANCE_REF:-compliance}?" || { warn "ยกเลิก"; exit 1; }
pilot_setup gate "$ENDPOINT"
pause

# ── 5 ────────────────────────────────────────────────────────────────────
stage "Credential ref: verify client_id แล้ว activate"
say "อ่าน token จาก Keychain ใน process, ตรวจ client_id = ${CHANNEL_ID} แล้วบันทึกแค่ fingerprint"
CREDENTIAL_REF_ID=$(pilot_setup credential)
write_env CXA_S2_CREDENTIAL_REF_ID "$CREDENTIAL_REF_ID"
pause

# ── 6 ────────────────────────────────────────────────────────────────────
stage "GitHub variables ของ provider job"
say "reference เท่านั้น (ไม่มี secret) — workflow อ่านผ่าน vars.*"
set_var CXA_S2_PILOT_TENANT_ID "$TENANT_ID"
set_var CXA_S2_CREDENTIAL_REF_ID "$CREDENTIAL_REF_ID"
set_var CXA_S2_APPROVED_WEBHOOK_ENDPOINT_DIGEST "$DIGEST"
note "ต้องมีสิทธิ์ admin/maintain ของ ${REPO}; ถ้าข้าม ให้เจ้าของ repo ตั้งค่าตามสรุปตอนท้าย"
pause

# ── 7 ────────────────────────────────────────────────────────────────────
stage "GitHub environment line-provider-pilot"
open_url "https://github.com/${REPO}/settings/environments/new"
step "Name: line-provider-pilot → Configure environment"
step "ติ๊ก Required reviewers แล้วเพิ่มผู้อนุมัติ provider run → Save protection rules"
note "ต้องใช้สิทธิ์ admin ของ repo"
pause "เมื่อบันทึกแล้ว กด Enter"
if gh api "repos/${REPO}/environments/line-provider-pilot" >/dev/null 2>&1; then
  printf '  %s✓%s พบ environment line-provider-pilot\n' "$GREEN" "$RESET"
else
  SKIPPED+=("GitHub environment line-provider-pilot + required reviewer (admin)")
  warn "ยังไม่พบ environment — เพิ่มในรายการที่ต้องทำเอง"
fi
pause

# ── 8 ────────────────────────────────────────────────────────────────────
stage "Self-hosted runner label line-pilot บนเครื่องนี้"
open_url "https://github.com/${REPO}/settings/actions/runners/new?arch=arm64&os=osx"
step "ทำตามคำสั่ง Download ในหน้านั้นในโฟลเดอร์ ~/actions-runner"
step "ตอน Configure เพิ่ม:  ./config.sh --url https://github.com/${REPO} --token <token> --labels line-pilot"
step "สร้างไฟล์ ~/actions-runner/.env ใส่ DATABASE_URL เดียวกับ ${ENV_FILE} (runner อ่านเข้า job env)"
step "เริ่ม runner:  cd ~/actions-runner && ./run.sh   (ค้างไว้ระหว่าง pilot)"
note "ต้องใช้สิทธิ์ admin ของ repo"
pause "เมื่อ runner ขึ้น Idle ในหน้า Runners แล้ว กด Enter"
if gh api "repos/${REPO}/actions/runners" --jq '.runners[].labels[].name' 2>/dev/null | grep -qx line-pilot; then
  printf '  %s✓%s พบ runner label line-pilot\n' "$GREEN" "$RESET"
else
  SKIPPED+=("self-hosted runner label line-pilot (admin) — ตรวจจาก API ไม่ได้หรือยังไม่ลง")
  warn "ตรวจ runner ไม่ได้ — เพิ่มในรายการที่ต้องทำเอง"
fi
pause

finish
note "ขั้นต่อไป: บอก agent ให้รัน PR01 — actual push (PR02) ต้องอนุมัติ proposal ด้วย digest ก่อนเสมอ"
